---
hide_body: false
fields:
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: repo
  label: Repo
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
